### PR TITLE
Added section to theory manual on Moeng surface boundary condition.

### PR DESCRIPTION
**Pull request by mbarone81**

### CODE REVIEW

**Comment by spdomin** [comment]
This looks fine. What is the order of this effort? Should we push to the src location before we update the manual?

Also, a ? for @jrood-nrel - the duplication of the manuals (and I see verification as well) needs to be addressed as we will have one for show via a webpage interface and another Latex-based approach with the full set of updates.

In general, I would like to see a resolution on the theme of duplication in NaluCFD.

**Comment by jrood-nrel** [comment]
@spdomin I don't have a solution for this. Sphinx can output PDF format, but it would take a commitment/sacrifice to Sphinx and RST format for the theory and verification manuals, and I think it was decided LaTeX was a requirement due to the PDF requirement. If LaTeX can output html, maybe I can work that into readthedocs. That's the only hope I have at the moment. Converting LaTeX -> RST (Sphinx) is not an option from what I have tried. At the moment though, my idea is just to remove the theory and verification manuals from readthedocs, and that they are only LaTeX. Though in that case, I think it would be helpful to have the PDFs prebuilt in the NaluDoc repo, so that I can at least link to them from readthedocs.

**Comment by sayerhs** [comment]
I would prefer to keep the documentation entirely in Sphinx with the Nalu codebase (instead of a separate repo) and enable the Sphinx `Makefile` which provides both `make latex` and `make latexpdf` targets. This will allow us to generate HTML, PDF (and intermediate .tex dumps) from the `.rst` files. 

This also simplifies the pull requests.

**Comment by spdomin** [comment]
Do we have an example of converting back and forth? Everyone knows Latex. Do I need to learn a new tool for Sphinx documentation?

Ideally, we could move back and forth. Can I write something in Latex and have S generate the rst file?

**Comment by sayerhs** [comment]
[Pandoc](http://pandoc.org/demos.html) is an option for converting Latex to RST. I believe some of the documentation was converted automatically using this? @gantech can you comment if you used `pandoc` to convert Nalu/NaluDoc, or did you do that manually?

**Comment by gantech** [comment]
I did use pandoc to convert most of the document. However, the pandoc conversion doesn't deal with equations, figures, subfigures and tables well. Significant manual intervention was required.

**Pull request merged**
